### ISSUE TITLE
Feature: Set to one of a list of values

### ISSUE THREAD

**Issue by MrFojo** [MisterJames/GenFu#106]
Set a property to one of the values from a list. Something like

`A.Configure<Apparel>()`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`.Fill(apparel => apparel.Type, `
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`type => OneOf({"Shirt","Trousers","Dress","Blouse","Skirt"});`

**Comment by dpaquette** [comment]
This works today as follows;

`A.Configure<Apparel>().Fill(apparel => apparel.Type).WithRandom(new []{"Shirt", "Trousers", "Dress", "Blouse", "Skirt"});`

**Comment by MisterJames** [comment]
@MrFojo This one's baked in already, let us know if you have any questions around it!
