### ISSUE TITLE
Hey please add this feature to your project ?

### ISSUE THREAD

**Issue by ashrafxcoder** [MisterJames/GenFu#110]
For string Properties

`GenFu.Configure<BlogPost>()`
                `.Fill(p => p.Description).AsLoremIpsumWords(400).AsTitle(p => p.Description)`
Or
               `.Fill(p => p.Description).AsLoremIpsumWords(400).ToTitleCase(p => p.Description)`
To change the description property to title case
From : "sed ipsum turpis vel pellentesque"
To : "Sed Ipsum Turpis Vel Pellentesque"

I am wrapping my head around the code to learn and add it myself but it would be great if you do that

As well as some more for helping with html paragraph and heading tag creation.

**Comment by MisterJames** [comment]
Hi @ashrafxcoder, check out version 1.3.3 to see the latest features as described here:

http://genfu.io/wireframe

You'll need the `GenFu.HtmlHelpers.Wireframes` that @EdCharbeneau is working on, I think it should be up in the near future.  Cheers!

**Comment by MisterJames** [comment]
@ashrafxcoder and just so you know, we're having a good discussion about how we might implement this, but not exactly as you suggest. 

We have a next major version (bit of a dream right now) where values are constructed through a pipeline. This would allow for templated construction based on generated properties as well as things like formatters (that would do things like capitalization as you're suggesting) but our current framework doesn't really allow for this.

I'm going to close this, but watch for v2 where this will be built in.  Cheers!

**Comment by ashrafxcoder** [comment]
Thank you for letting me know....
I am looking forward for all this really cool stuff....
Happy Coding...
