### ISSUE TITLE
Filling a text list results in zero entries (syntax worked on AngelaSmith version)

### ISSUE THREAD

**Issue by JimKay1941** [MisterJames/GenFu#126]
This syntax was copied from AngelaSmith, where it works, to GenFu where it produces an empty list as output. There are no error messages.

.Fill(p => p.Skills, () => new List<string>() { "Math", "Science", "History" })

**Comment by dpaquette** [comment]
This is definitely a bug. That syntax should work

**Comment by stimms** [comment]
I went and put in a test for this because it seemed odd that it didn't work. 

``` 
        [Fact]
        public void Should_fill_from_a_configured_list()
        {
            GenFu.Reset();
            GenFu.Configure<BlogPost>().Fill(x => x.Tags, new List<string> { "default" });
            var result = A.New<BlogPost>();
            Assert.Equal("default", result.Tags.Single());
        }
```

That test passed but maybe I'm interpreting what is expected here incorrectly. I also tried

``` 
        [Fact]
        public void Should_fill_from_a_configured_list()
        {
            GenFu.Reset();
            GenFu.Configure<BlogPost>().Fill(x => x.Tags, () => new List<string> { "default" });
            var result = A.New<BlogPost>();
            Assert.Equal("default", result.Tags.Single());
        }
```

I wonder if it might not be the lack of generic in your example code. Could you try

```
.Fill(p => p.Skills, () => new List<string>() { "Math", "Science", "History" })
```

Instead?

**Comment by JimKay1941** [comment]
Something has become confused. The "Could you try..." you have provided is PRECISELY what I submitted to you as the NOT WORKING version.

Here is the Person data model file:
`using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SimpleSite.Models
{
    public class Person
    {
        public Person()
        {
            Skills = new HashSet<string>();
            BirthDate = DateTime.Now.AddYears(-20);
        }

        public int PersonId { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public DateTime BirthDate { get; set; }

        [Required]
        [UIHint("BooleanButtonLabel")]
        public bool LikesMusic { get; set; }

        [Required]
        [EmailAddress]
        public string EmailAddress { get; set; }

        public ICollection<string> Skills { get; set; }
    }
`
Here is the Angie version of the "PersonController" which does work. The 'Skills' list for every person contains the three items: "Math" "Science" and "History."
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Angela.Core;
using SimpleSite.Models;

namespace SimpleSite.Controllers
{
    public class PersonController : BaseController
    {
        private static ICollection<Person> _people;

        static PersonController()
        {
            _people = Angie.Configure<Person>()
                .Fill(p => p.BirthDate)
                .AsPastDate()
                .Fill(p => p.LikesMusic)
                .WithRandom(new List<bool>() { true, true, true, false, false })
                .Fill(p => p.Skills, () => new List<string>() { "Math", "Science", "History" })
                .MakeList<Person>(20);
        }

        // GET: Person
        public ActionResult Index()
        {
            return View(_people);
        }

        public ActionResult SearchPeople(string searchText)
        {
            var term = searchText.ToLower();
            var result = _people
                .Where(p =>
                    p.FirstName.ToLower().Contains(term) ||
                    p.LastName.ToLower().Contains(term)
                );

            return PartialView("_SearchPeople", result);
        }

        public ActionResult Create()
        {
            var person = new Person();
            return View(person);
        }

        [HttpPost]
        public ActionResult Create(Person person)
        {
            if (ModelState.IsValid)
            {
                _people.Add(person);
                Success(string.Format("<b>{0}</b> was successfully added to the database.", person.FirstName), true);
                return RedirectToAction("Index");
            }
            Danger("Looks like something went wrong. Please check your form.");
            return View(person);
        }

    }
}`
Each and every Person generated has the three Skills in their Skills list.

Here is the GenFu version of the PersonController which does NOT work because each and every Person generated has and empty Skills list.
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GenFu;
using SimpleSite.Models;

namespace SimpleSite.Controllers
{
    public class PersonController : BaseController
    {
        private static ICollection<Person> _people;

        static PersonController()
        {
            GenFu.GenFu.Configure<Person>()
                .Fill(p => p.BirthDate)
                .Fill(p => p.LikesMusic)
                .WithRandom(new List<bool>() { true, true, true, false, false })
                .Fill(p => p.Skills, () => new List<string>() { "Math", "Science", "History" });
            _people = GenFu.GenFu.ListOf<Person>();
        }

        // GET: Person
        public ActionResult Index()
        {
            return View(_people);
        }

        public ActionResult SearchPeople(string searchText)
        {
            var term = searchText.ToLower();
            var result = _people
                .Where(p =>
                    p.FirstName.ToLower().Contains(term) ||
                    p.LastName.ToLower().Contains(term)
                );

            return PartialView("_SearchPeople", result);
        }

        public ActionResult Create()
        {
            var person = new Person();
            return View(person);
        }

        [HttpPost]
        public ActionResult Create(Person person)
        {
            if (ModelState.IsValid)
            {
                _people.Add(person);
                Success(string.Format("<b>{0}</b> was successfully added to the database.", person.FirstName), true);
                return RedirectToAction("Index");
            }
            Danger("Looks like something went wrong. Please check your form.");
            return View(person);
        }

    }
}`

**Comment by stimms** [comment]
I took your model 

```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SimpleSite.Models {
  public class Person {
   public Person() {
    Skills = new HashSet();
    BirthDate = DateTime.Now.AddYears(-20);
   }

   public int PersonId { get; set; }

   [Required]
   public string FirstName { get; set; }

   [Required]
   public string LastName { get; set; }

   [Required]
   public DateTime BirthDate { get; set; }

   [Required]
   [UIHint("BooleanButtonLabel")]
   public bool LikesMusic { get; set; }

   [Required]
   [EmailAddress]
   public string EmailAddress { get; set; }

   public ICollection < string > Skills { get; set; }
  }
}```

and, after fixing the incorrect initialization of the HashSet to a non-generic managed to duplicate your problem. It looks to me like initializing the HashSet in the constructor is the problem. I'd bet it is because we only fill properties that have default values and a non-null list isn't a default value. 

We could fill lists which are empty, I think that's a safe change to make but we should also consider this in conjunction with #121  which would be a more global solution to this sort of problem. I'll go ahead and add the filling of empty lists.

**Comment by JimKay1941** [comment]
For me, the puzzle arises because almost exactly the same code worked with the Alice version and that code came from a tutorial written by Mr. James, himself. 

(The GenFu version was posted by another person who did not seem to realize it wasn't working.)

I'll look at #121 shortly.

**Comment by JimKay1941** [comment]
I cloned GenFu (about 2 hours ago), built it, and pointed my own project's reference to that .dll.

Now GenFu is working as I had expected. 

Thank you to everyone who participated in this issue.
