### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by os1r1s110** [MisterJames/GenFu#127]
Not really an issue, didn't know where to ask. Just wanted to know you had any plans on releasing the latest changes to NuGet anytime soon? I'm eager to use the new nullable types automatic fill :)

Thanks in advance!

**Comment by stimms** [comment]
I think there is enough for a release once #128 is done.

**Comment by os1r1s110** [comment]
Glad to hear that! I'll wait patiently :)

Thanks for your work (and the other monsters hehe), this is a real time saver!

**Comment by os1r1s110** [comment]
Is anything still blocking the update to NuGet? I saw #128 was merged so I wondered if you planned on updating anytime soon :) 

Thanks again and don't think I want to rush you, I know it's open source and you guys do it on your spare time, I fully understand it. I'm just eager to use the updated goodies :P

**Comment by os1r1s110** [comment]
Hey there, me again, just wanted to know if there was any update regarding the release of the updated package to NuGet?  I saw the issue #132 so I guess it is a road block but would like to get a general idea of when/if you plan to release in the near future :)

Thanks in advance!

**Comment by dpaquette** [comment]
New release was pushed last night. It is available on NuGet now
