### ISSUE TITLE
Set nullables

### ISSUE THREAD

**Issue by stimms** [MisterJames/GenFu#13]
Angela seems to take issue with nullables. She doesn't set them at all! I'd like to see Angela set a value some of the time. Perhaps in all cases she could set a value and then evil Angela could randomly set the values to nullable as a sort of input fuzzing.

**Comment by M-Zuber** [comment]
Have run into this problem today. Any news?

**Comment by gpltaylor** [comment]
I have submitted a Pull Request that solves this problem for DateTime. This includes a Seed value for controlling the percentage of Null values allowed (Fuzzing). This is also required for other Nullable Types like Int?

**Comment by fugaku** [comment]
Any news on this one ?

**Comment by gpltaylor** [comment]
@fugaku 
 I believe this is resolved. My fix was merged into dev https://github.com/MisterJames/GenFu/pull/53

**Comment by os1r1s110** [comment]
Has there been an implementation for other nullable types than DateTime?
