### ISSUE TITLE
Can't build the solution

### ISSUE THREAD

**Issue by ngruson** [MisterJames/GenFu#139]
I can't get the sources to build after cloning the repo. I'm running Visual Studio Enterprise 2017, version 15.6.6.
After deleting global.json from the root, I can build GenFu and GenFu.HtmlHelpers but still not GenFu.Tests:

NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Build started: Project: GenFu, Configuration: Debug Any CPU ------
1>GenFu -> C:\_GitHub\GenFu\src\GenFu\bin\Debug\net46\GenFu.dll
1>GenFu -> C:\_GitHub\GenFu\src\GenFu\bin\Debug\net461\GenFu.dll
1>GenFu -> C:\_GitHub\GenFu\src\GenFu\bin\Debug\netstandard1.3\GenFu.dll
1>GenFu -> C:\_GitHub\GenFu\src\GenFu\bin\Debug\net45\GenFu.dll
2>------ Build started: Project: GenFu.Tests, Configuration: Debug Any CPU ------
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit 2.3.0 -> xunit.assert 2.3.0 -> NETStandard.Library 1.6.1 -> Microsoft.NETCore.Platforms (>= 1.1.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NETCore.Platforms (>= 1.0.2)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit 2.3.0 -> xunit.core 2.3.0 -> xunit.extensibility.core 2.3.0 -> NETStandard.Library 1.6.1 -> Microsoft.NETCore.Platforms (>= 1.1.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NETCore.Platforms (>= 1.0.2)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit 2.3.0 -> xunit.core 2.3.0 -> xunit.extensibility.execution 2.3.0 -> NETStandard.Library 1.6.1 -> Microsoft.NETCore.Platforms (>= 1.1.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NETCore.Platforms (>= 1.0.2)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NET.Test.Sdk from 15.0.0 to 15.0.0-preview-20170106-08. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit.runner.visualstudio 2.3.0 -> Microsoft.NET.Test.Sdk (>= 15.0.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NET.Test.Sdk (>= 15.0.0-preview-20170106-08)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit 2.3.0 -> xunit.assert 2.3.0 -> NETStandard.Library 1.6.1 -> Microsoft.NETCore.Platforms (>= 1.1.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NETCore.Platforms (>= 1.0.2)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit 2.3.0 -> xunit.core 2.3.0 -> xunit.extensibility.core 2.3.0 -> NETStandard.Library 1.6.1 -> Microsoft.NETCore.Platforms (>= 1.1.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NETCore.Platforms (>= 1.0.2)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit 2.3.0 -> xunit.core 2.3.0 -> xunit.extensibility.execution 2.3.0 -> NETStandard.Library 1.6.1 -> Microsoft.NETCore.Platforms (>= 1.1.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NETCore.Platforms (>= 1.0.2)
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NET.Test.Sdk from 15.0.0 to 15.0.0-preview-20170106-08. Reference the package directly from the project to select a different version. 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> xunit.runner.visualstudio 2.3.0 -> Microsoft.NET.Test.Sdk (>= 15.0.0) 
2>C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj : error NU1605:  GenFu.Tests -> Microsoft.NET.Test.Sdk (>= 15.0.0-preview-20170106-08)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Extensions.DependencyModel" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>GenFu.Tests -> C:\_GitHub\GenFu\tests\GenFu.Tests\bin\Debug\netcoreapp1.0\GenFu.Tests.dll
2>Done building project "GenFu.Tests.csproj" -- FAILED.
2>GenFu.Tests -> C:\_GitHub\GenFu\tests\GenFu.Tests\bin\Debug\net451\GenFu.Tests.dll
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

I tried to install the referenced packages again in the test project, but I get stuck when trying to install Microsoft.NetCore.Platforms:

Restoring packages for C:\_GitHub\GenFu\tests\GenFu.Tests\GenFu.Tests.csproj...
System.ArgumentException: Package with id "Microsoft.NETCore.Platforms" does not exist.

Any pointers for this?

**Comment by Jamaxack** [comment]
Rebuild All succeeded in Visual Studio 2019 version 16.4.2, try upgrading your Visual Studio to latest version.
