### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by knight1219** [MisterJames/GenFu#152]
I've used this project for years now and love it, even took a copy and pushed it to compile with .net core 2.2. But is there going to be anymore official support going forward? The last thing that happened was a merge of a PR last year.

I would be happy to push up my version with .net core support and some other interesting features (using Data annotations in order to create good vs bad versions of objects for passing unit tests).

**Comment by dpaquette** [comment]
The project isn't dead but we do need to dedicate a little more time to it.  We are happy to review your pull requests adding .NET Core support and potentially other features.

**Comment by knight1219** [comment]
I'll try and push it up to a fork and see if I can get a list of all the changes I have made. A lot of the changes where ones I needed for unit tests and testing "bad" versions of an object.
