### ISSUE TITLE
[ValueTypes] filling

### ISSUE THREAD

**Issue by xperiandri** [MisterJames/GenFu#165]
While filling a value type I discovered that you don't have a check that checks a value type default value.
So I implemented the one and can create a pull request.
However, I would also like to add public fields filling too. Do you accept that?

**Comment by dpaquette** [comment]
Submit a pull request and we will review. Those both sound like useful features

**Comment by dpaquette** [comment]
@xperiandri  Did #166 fully implement this feature for you?

**Comment by xperiandri** [comment]
It works if you try to get the instance of the configured type.
But if you have 2 configured types and one takes another in the constructor, then that input instance is empty.

**Comment by xperiandri** [comment]
Yes
