### ISSUE TITLE
Method Filler idea

### ISSUE THREAD

**Issue by MaximRouiller** [MisterJames/GenFu#23]
``` csharp
    GenFu.Configure<Person>()
        .MethodFill(x => x.SetMiddleName(GenFu.Fill<string>(), "my default"));
```

This would you to be explicit about how you fill parameters and would also allow default parameters for same typed parameters. 

I haven't installed the tool, I haven't tested it. Just an idea. :smiley:

**Comment by stimms** [comment]
Hi @maximrouiller I'm afraid that I don't really understand what you're asking for here.

**Comment by MaximRouiller** [comment]
Here's the method filler example in the repo readme:

    GenFu.Configure<Person>()
        .MethodFill<string>(x => x.SetMiddleName(null))
    var post = A.New<Person>();

Here's my suggested implementation instead:

    GenFu.Configure<Person>()
        .MethodFill<string>(x => x.SetMiddleName(GenFu.Fill<string>()))
    var post = A.New<Person>();

Maybe I actually want to use a `null` parameter. You could use `GenFu.Fill<T>()` as a placeholder instead of `null`.
