### ISSUE TITLE
Don't use `A.` prefix

### ISSUE THREAD

**Issue by luisrudge** [MisterJames/GenFu#32]
[FakeItEasy](http://fakeiteasy.github.io/), a popular mocking library for .NET, already uses the `A.` prefix. Since both of your projects are great for writing tests, I recommend you change your prefix to something else, so we can GenFu with FakeItEasy without any issues.

**Comment by stimms** [comment]
Humm it is kind of a naming conflict in the English language. I don't know how we would solve this without radically changing the api. Ideas that come to mind (without checking to see if any are viable) are

Static using
Creating a second namespace for compatibility which uses a different key word

**Comment by luisrudge** [comment]
Sure, I know `A` means just `A` in english and I'm not claiming FakeItEasy "owns" that prefix, but since this is a new project, I think it's easier to change it here than in FakeItEasy.

**Comment by stimms** [comment]
I'd rather that nobody has to change their API but a conflict in naming is certainly undesirable. I'd like to explore some options before we go about changing APIs wholesale. Worst case scenario we could use `One.` and we might be able to just put that in a wrapper class which we keep in a `Genfu.Compat` namespace.

**Comment by luisrudge** [comment]
Great!

**Comment by dpaquette** [comment]
A is essentially just an alias for the `GenFu`. If you don't want to use A you can use `GenFu` instead.

**Comment by luisrudge** [comment]
Oh, nice! I'll close this then. THanks

**Comment by stimms** [comment]
You would still have a name conflict though, right?

**Comment by luisrudge** [comment]
Sure, but only in the first time. After you import GenFu and FakeItEasy, it should have no conflict
