### ISSUE TITLE
Suggestion: respect MaxLengthAttribute

### ISSUE THREAD

**Issue by natemcmaster** [MisterJames/GenFu#49]
Automatically truncate data when inserting into string properties with a defined [MaxLengthAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.maxlengthattribute%28v=vs.110%29.aspx)

**Comment by gpltaylor** [comment]
It would be great to support a number of different Attributes. For example RegularExpressionAttribute. However with most thing, there might need to be an option to turn this on/off? Also writing code to conform to these attributes could be hard work (performance wise).

**Comment by natemcmaster** [comment]
Closing as this bug is stale.
