### ISSUE TITLE
Is there any filler for body?

### ISSUE THREAD

**Issue by Codenator81** [MisterJames/GenFu#55]
If I need fill field with same thing like blog post body field. How I can do this?

**Comment by dpaquette** [comment]
We don't have anything for this yet but it is definitely needed. 

Ideally I would like to see something along the lines of :
```
A.ListOf<BlogPost>().Fill(b => b.Contents).WithParagraphs(3)
```
Where the parameter is the number of paragraphs to generate when filling the property.

**Comment by Codenator81** [comment]
@dpaquette This will be great feature!

**Comment by mrahhal** [comment]
+1 We really need this.
