### ISSUE TITLE
Filling boolean values

### ISSUE THREAD

**Issue by mrahhal** [MisterJames/GenFu#61]
I'm not sure if this exists, it would be nice to specify how to fill boolean values.

Something like:

```c#
A
    .Config<Model>()
    .Fill(m => m.IsFeatured, ...)
// Actually, I'm not sure how this would look, but I'd like to specify a percentage
// of the result being true. So "0.3" would fill IsFeatured as true 30% of the time.
```

Does something like this exist, or at least is this doable?

**Comment by gpltaylor** [comment]
This is possible already. There is a property in Defaults called seedPercentage. Setting this value to 0.30 will make this Null 30% of the time (on average). Note: as this is a random seed 30% can not be guaranteed unless the number of results in known before hand.

**Comment by stimms** [comment]
Sounds like perhaps this is good to go
