### ISSUE TITLE
Supporting platform target 5.4 instead of dnxcore5

### ISSUE THREAD

**Issue by JuergenGutsch** [MisterJames/GenFu#63]
I think you should support platform target 5.4 (dotnet5.4) instead of dnxcore5 to support more frameworks and platforms. David Fowler talked about it at the MVP Summit 2015 and showed a document about it: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

Should be a simple change in the project.json

**Comment by clarkis117** [comment]
This issue should be closable now, due to GenFu supporting .NET Standard #91 #96 

cc: @stimms @MisterJames @dpaquette

**Comment by JuergenGutsch** [comment]
Great. Yes, can be closed
