### ISSUE TITLE
ListOf<T>(int personCount)

### ISSUE THREAD

**Issue by MaximRouiller** [MisterJames/GenFu#74]
Well... what if I want something else? :smile: 

https://github.com/MisterJames/GenFu/blob/d0f01bd713dca11b9ba8d07f9d7a9412255dfae0/src/GenFu/GenFu.cs#L79

I propose that we rename the parameter name to something more generic.

**Comment by dpaquette** [comment]
Great idea @MaximRouiller 

Perhaps `itemCount` would be more appropriate

**Comment by MaximRouiller** [comment]
That would actually be more in line with the desired experience. :+1:

**Comment by dpaquette** [comment]
I would like to try fixing this

**Comment by MisterJames** [comment]
Sounds good @dpaquette, please create a PR and I'll help you through it.

**Comment by MaximRouiller** [comment]
Am I in a demo!? :smile:

**Comment by MaximRouiller** [comment]
You guys are awesome.

**Comment by MisterJames** [comment]
Closed by #78.
