### ISSUE TITLE
Wrong semantics for member initialization

### ISSUE THREAD

**Issue by vhe1** [MisterJames/GenFu#87]
Given the same objects as in https://github.com/MisterJames/GenFu/issues/86 I find it hard to initialize child collections.

For some reason the fillers get applied _before_ the constructor is called. So, if I use the EF7 scaffolding generator, which creates constructors like for "Questions" in the other issue, the child collections will be overwrittem by the constructor after .Fill has been applied.

this makes things like

    .Fill(q => q.QuestionAnswers,
        ()=>
        {
            List<QuestionAnswers> answers = A.ListOf<QuestionAnswers>(3); // get me 3 answers
            answers = answers.Select((i, j) =>
            {
                i.AnswerNo = j + 1; // number them properly
                return i;
            }).ToList();
            answers[rng.Next(answers.Count - 1)].IsCorrect = true; // one correct answer
            return answers;
        }
        );
impossible unfortunately.

It would be phantastic if the fillers had the same semantics as member initializers:

    new Questions
    {
        Id = Guid.NewGuid(),
        QuestionType = "Text",
        QuestionText = "xxx",
        CategoryId = context.Categories.First().PK,
        QuestionAnswers = new List<QuestionAnswers>
        {
            new QuestionAnswers
            {
                AnswerNo = 1,
                IsCorrect = true,
                Text = "A"
            },
            new QuestionAnswers
            {
                AnswerNo = 2,
                IsCorrect = false,
                Text = "B"
            },
            new QuestionAnswers
            {
                AnswerNo = 3,
                IsCorrect = false,
                Text = " C"
            }
        }
    }

gives me the properly filled in subcollection because the member initialization is executed _after_ the constructor of "Questions".

**Comment by dpaquette** [comment]
We initialize child collections like you describe all the time without problems. It would not be possible for us to fill a collection before the constructor because there would be no object to fill at that time. I suspect something else is happening here. 

Can you try a very simple Filler for you collection to confirm whether or not it is working?

```
.Fill(q => q.QuestionAnswers,
    ()=> { return  A.ListOf<QuestionAnswers>(3); // get me 3 answers });
    );

```

**Comment by MisterJames** [comment]
@vhe1 closing as we haven't seen any activity here in a while, but feel free to reopen if you're still having troubles.
