### ISSUE TITLE
Feature Request: Add own resource-files

### ISSUE THREAD

**Issue by code1line** [MisterJames/GenFu#90]
It would be nice, if you can register a property-name and the corresponding resource-file (textfile) within the configuration. So it would be open for all types and languages!

**Comment by dpaquette** [comment]
Paging @MisterJames 
I thought we supported this out of the box already

**Comment by code1line** [comment]
How about the syntax? I have read the docs, but haven't seen anything like that. Thx in advance!

**Comment by dpaquette** [comment]
Our docs are definitely lacking on some of the extension points.
The key is somewhere in the ResourceLoader (https://github.com/MisterJames/GenFu/blob/master/src/GenFu/ResourceLoader.cs)

It first looks for files in the application path and there is some logic in there about culture specific things. If nothing is found in the app path then it defaults to the built in resource files. 

It's possible this feature isn't fully fleshed out. I will try to provide some better docs.

**Comment by MisterJames** [comment]
The docs for this will be tracked in via #93.
