### ISSUE TITLE
Updating to .NET Core RTM and targeting .NET Standard

### ISSUE THREAD

**Issue by clarkis117** [MisterJames/GenFu#91]
Hello, I’m creating this issue to start a conversation about updating GenFu to .NET Core 1.0.0 and to target the new .NET Standard system. I’m also working on a pull request that updates the project.json files for this. Although, it still has to be decided which .NET Standard profile to target. I’m partial to targeting .NET Standard 1.6 and .NET Framework 4.5.1 like ASP.NET Core. Please let me know your thoughts, feelings, or concerns.

Working Branch Here: https://github.com/clarkis117/GenFu

**Comment by clarkis117** [comment]
Update: Project.json files and namespaces have been migrated and the commit is up on the working branch. However, the solution is currently getting build errors due to the website's dependency on DNX. I am currently working on porting the website's dynamic code compilation over to .NET Core, so it no longer depends on DNX.

**Comment by MisterJames** [comment]
@clarkis117 That. Is. Awesome. Thanks a tonne!

**Comment by dpaquette** [comment]
@clarkis117 Awesome work! 
You might be right about the DNX thing. Take a look at the change I had to make here when I upgraded to RTM: https://github.com/dpaquette/TagHelperSamples/commit/654db419e267a25c205b1d5f1da353449c24e363#diff-b8f19466674f2b8fadeacb89f07165e8

**Comment by clarkis117** [comment]
@dpaquette It looks like the DNX "runtime targeting errors" were being caused by a dirty nuget cache on my dev box, but I did change the DNX references in the xproj file for the website to reference the dotnet tooling like in your taghelper commit. In the other, xproj files it was causing the tooling to add launchSettings.json files, so I didn't remove them: https://github.com/clarkis117/GenFu/commit/8fb3b8d86c0c6ccdd523243708edccece932ae3a

**Comment by clarkis117** [comment]
Woot good news, I got the code generation working for the website; however, my solution is just as hacky as the original. I couldn’t find much documentation around how ILibraryExporter works in the new dotnet cli world… I even found two distinct implementations of it which both appear to work. My hacky solution gets the MetadataReferences to the other assemblies from a list of hardcoded types.

```
public static class SourceCodeHelpers
	{
		public static readonly Type[] SupportedTypes = new Type[]
		{
			typeof(Object),
			typeof(short),
			typeof(float),
			typeof(Int32),
			typeof(Int16),
			typeof(double),
			typeof(decimal),
			typeof(Guid),
			typeof(long),
			typeof(ulong),
			typeof(uint),
			typeof(ushort),
			typeof(bool),
			typeof(string),
			typeof(DateTime)
		};

		public static MetadataReference GetMeta(this Type type)
		{
			return MetadataReference.CreateFromFile(type.GetTypeInfo().Assembly.Location);
		}
	}
```

https://github.com/clarkis117/GenFu/commit/ba587432ce10f4ce22daf6c678e8471d36a4b5d0

I'm also asking around (badgering Scott Hanselman on twitter) seeing if I can get the team behind the new dot.net website to post some details about the interactive code tutorial system (https://www.microsoft.com/net/tutorials/csharp/getting-started/hello-world). The editor is already open source on the Microsoft Github (https://github.com/Microsoft/monaco-editor), but the implementation details and the Roslyn backend used aren’t documented or opensource.

**Comment by clarkis117** [comment]
I'm cleaning up my work on the website's code compilation pipeline. I should have a PR submitted today. This will be my first PR on someone else's project so feedback is appreciated.

**Comment by clarkis117** [comment]
@MisterJames @dpaquette Pull Request is in, let me know how it goes :shipit:

**Comment by clarkis117** [comment]
This can be closed now
