### ISSUE TITLE
Strings are empty in 1.2.0

### ISSUE THREAD

**Issue by EdCharbeneau** [MisterJames/GenFu#98]
I think there is an issue with the NuGet package for 1.2.0 where the [Resource](https://github.com/MisterJames/GenFu/tree/master/src/GenFu/Resources) are not included in the package, this results in an empty string for all string values.

A.New<Person>().FirstName //=> ""
A.New<Person>().LastName //=> ""
A.New<Person>().Age //=> 35

**Comment by MisterJames** [comment]
@EdCharbeneau I think I got it. 

I've updated the way the resources are loaded and broken out the declaration/assignment of the resource stream and it's working from a local package build. I'm uploading now to https://www.nuget.org/packages/GenFu/1.2.1 (just waiting for the index to update).

Thanks for notifying us!

**Comment by MisterJames** [comment]
So...the fix, btw...if you pull down the nupkg for 1.2.0 and use JustDecompile the resources are actually in there. I haven't nailed down why they weren't working, but seemingly it appears as though this bump to the specification of the embed for the resources and the breakout of the assignment seem to have changed _something_.

Commits: 
https://github.com/MisterJames/GenFu/commit/e0cfa5cfe44c5c3747c0ae62d91547442f024718
https://github.com/MisterJames/GenFu/commit/b24714802d4875debb9a8f74ecd6269cee8420bf

**Comment by EdCharbeneau** [comment]
Fixed by PR #115 

Note: Version number on the NuGet package for this fix is 1.4.4 however, GenFu.csproj still shows 1.3.3
